deploy to EKS

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -1,62 +1,82 @@
 name: "IAC"
 
 on:
-    push:
-        branches:
-            - main
-            - stage
-        paths: 
-            - terraform/**
-    pull_request: 
-        branches:
-            - main
-        paths:
-            - terraform/**
+  push:
+    branches:
+      - main
+      - stage
+    paths:
+      - terraform/**
+  pull_request:
+    branches:
+      - main
+    paths:
+      - terraform/**
 
 env:
-    # AWS Configure
-    AWS_ACCESS_KEY_ID : ${{secrets.AWS_ACCESS_KEY_ID}}
-    AWS_SECRET_ACCESS_KEY : ${{secrets.AWS_SECRET_ACCESS_KEY}}
-    # S3 Bucket for terraform state
-    BUCKET_TF_STATE : ${{secrets.BUCKET_TF_STATE}}
-    AWS_REGION: us-east-2
-    EKS_CLUSTER: app-eks
+  # AWS Configure
+  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
+  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
+  # S3 Bucket for terraform state
+  BUCKET_TF_STATE: ${{secrets.BUCKET_TF_STATE}}
+  AWS_REGION: us-east-2
+  EKS_CLUSTER: app-eks
 
 jobs:
-    terraform:
-        name: "Apply terraform code change"
-        runs-on: ubuntu-latest
-        defaults:
-            run:
-                shell: bash
-                working-directory: ./terraform
-        steps:
-            - name: Copy code from respository to ubuntu server
-              uses: actions/checkout@v4
+  terraform:
+    name: "Apply terraform code change"
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+        working-directory: ./terraform
+    steps:
+      - name: Copy code from respository to ubuntu server
+        uses: actions/checkout@v4
 
-            - name: Install terraform in ubuntu
-              uses: hashicorp/setup-terraform@v2
-            
-            - name: Terraform init
-              id: init
-              run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
+      - name: Install terraform in ubuntu
+        uses: hashicorp/setup-terraform@v2
 
-            - name: Terraform format
-              id: format
-              run: terraform fmt -check
+      - name: Terraform init
+        id: init
+        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
 
-            - name: Terraform validate
-              id: validate
-              run: terraform validate
+      - name: Terraform format
+        id: format
+        run: terraform fmt -check
 
-            - name: Terraform plan
-              id: plan
-              run: terraform plan -input=false -out planfile
-              continue-on-error: true
-            
-            # If plan status has some wrong, job will fail
-            - name: Terraform plan status
-              id: plan-status
-              if: steps.plan.outcome == 'failure'
-              run: exit 1
-        
+      - name: Terraform validate
+        id: validate
+        run: terraform validate
+
+      - name: Terraform plan
+        id: plan
+        run: terraform plan -input=false -out planfile
+        continue-on-error: true
+
+      # If plan status has some wrong, job will fail
+      - name: Terraform plan status
+        id: plan-status
+        if: steps.plan.outcome == 'failure'
+        run: exit 1
+
+      - name: Terraform apply
+        id: terraform-apply
+        if: github.ref == 'ref/heads/main' && github.event_name == 'push'
+        run: terraform apply -auto-approve -input=false -parallelism=1 planfile
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
+          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
+          aws-region: ${{env.AWS_REGION}}
+
+      - name: Get Kube config file
+        id: get-kube-config
+        if: steps.terraform-apply.outcome == 'success'
+        run: aws eks update-kubeconfig --region ${{env.AWS_REGION}} --name ${{env.EKS_CLUSTER}}
+
+      - name: Apply Kube
+        if: steps.terraform-apply.outcome == 'success' && steps.get-kube-config.outcome == 'success'
+        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
